
filetype plugin indent on
set tabstop=4

"set t_Co=256
set background=dark
colorscheme eldar

set hlsearch

source ~/.vim/plugins/ale.vim
nnoremap <F12> :ALEToggle<CR>

"24 bit color
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

